### ISSUE TITLE
Compile error, Different errors in Windows and Android platforms

### ISSUE THREAD

**Issue by RHamidR** [jlaine/wilink#2]
I want to compile this project in Qt 5.4 But i faced some errors!!
I provided the 3rdparty dependencies and tried to compile the project but it shows the following errors in both of Android and Windows compilation.
How Could i compile this project and get the execution files?

"Error while building/deploying project wilink (kit: Desktop Qt 5.4.0 MinGW 32bit)"
![desktop 7 compile errors](https://cloud.githubusercontent.com/assets/10092307/6216195/d157d7a0-b61c-11e4-9fd7-7eeb020be179.jpg)

Compile Log:

C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:63:74: error: expected '}' before ';' token
         QT_WA( { mutex = CreateMutexW(NULL, FALSE, (WCHAR*)mname.utf16()); },
                                                                          ^
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:63:74: error: expected ')' before ';' token
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:63:77: error: expected primary-expression before ',' token
         QT_WA( { mutex = CreateMutexW(NULL, FALSE, (WCHAR*)mname.utf16()); },
                                                                             ^
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:64:16: error: expected primary-expression before '{' token
                { mutex = CreateMutexA(NULL, FALSE, mname.toLocal8Bit().constData()); } );
                ^
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:64:88: error: expected primary-expression before ')' token
                { mutex = CreateMutexA(NULL, FALSE, mname.toLocal8Bit().constData()); } );
                                                                                        ^
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp: At global scope:
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:70:5: error: expected unqualified-id before 'else'
     else {
     ^
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlocalpeer.cpp:200:1: error: expected '}' at end of input
 }
 ^
In file included from C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlocalpeer.cpp:59:0:
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp: In member function 'void* QtLP_Private::QtLockedFile::getMutexHandle(int, bool)':
C:\Qt\QTWorkSpace\wilink-master\src\3rdparty\qtsingleapplication\qtlockedfile_win.cpp:69:5: warning: control reaches end of non-void function [-Wreturn-type]
     }

"Error while building/deploying project wilink (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.4.0))"
![android 2 compile errors](https://cloud.githubusercontent.com/assets/10092307/6216423/5b86dcc6-b61f-11e4-8c63-bc9411a681aa.jpg)

Compile Log

In file included from C:\Qt\Qt5.4.0\5.4\android_armv7\include/QtCore/qatomic.h:34:0,
                 from C:\Qt\Qt5.4.0\5.4\android_armv7\include/QtCore/qrefcount.h:37,
                 from C:\Qt\Qt5.4.0\5.4\android_armv7\include/QtCore/qbytearray.h:37,
                 from C:\Qt\Qt5.4.0\5.4\android_armv7\include\QtCore/qurl.h:38,
                 from C:\Qt\Qt5.4.0\5.4\android_armv7\include\QtCore/QUrl:1,
                 from C:\Qt\QTWorkSpace\wilink-master\src\qnetio\src\filesystem\file.cpp:20:
C:\Qt\Qt5.4.0\5.4\android_armv7\include/QtCore/qglobal.h:684:85: error: expected ';' at end of input
 #define Q_STATIC_ASSERT_X(Condition, Message) static_assert(bool(Condition), Message)
                                                                                     ^
C:\Qt\Qt5.4.0\5.4\android_armv7\include\QtCore/qplugin.h:139:5: note: in expansion of macro 'Q_STATIC_ASSERT_X'
     Q_STATIC_ASSERT_X(false, "Old plugin system used")
     ^
C:\Qt\QTWorkSpace\wilink-master\src\qnetio\src\filesystem\file.cpp:141:1: note: in expansion of macro 'Q_EXPORT_STATIC_PLUGIN2'
 Q_EXPORT_STATIC_PLUGIN2(local_filesystem, LocalFileSystemPlugin)
 ^
C:\Qt\Qt5.4.0\5.4\android_armv7\include/QtCore/qglobal.h:684:47: error: static assertion failed: Old plugin system used
 #define Q_STATIC_ASSERT_X(Condition, Message) static_assert(bool(Condition), Message)
                                               ^
C:\Qt\Qt5.4.0\5.4\android_armv7\include\QtCore/qplugin.h:139:5: note: in expansion of macro 'Q_STATIC_ASSERT_X'
     Q_STATIC_ASSERT_X(false, "Old plugin system used")
     ^
C:\Qt\QTWorkSpace\wilink-master\src\qnetio\src\filesystem\file.cpp:141:1: note: in expansion of macro 'Q_EXPORT_STATIC_PLUGIN2'
 Q_EXPORT_STATIC_PLUGIN2(local_filesystem, LocalFileSystemPlugin)
 ^

**Comment by jlaine** [comment]
On 02/16/2015 06:49 PM, Hammer wrote:
>
> I want to compile this project in Qt 5.4 But i faced some errors!!
> I provided the 3rdparty dependencies and tried to compile the project
> but it shows the following errors in both of Android and Windows
> compilation.
> How Could i compile this project and get the execution files?
>

wiLink was never fully ported to Qt 5. I had started, but never
finished, and have since moved on to other projects.

Cheers,
Jeremy

**Comment by RHamidR** [comment]
Thank you @jlaine.
Can you suggest me some projects based on QXMPP that are compatible with Qt5 and Android?

over all, thank you for your hard work on these helpful projects

**Comment by jlaine** [comment]
Just FYI, the latest wiLink code is ported to Qt5, so this issue should be solved.
