### ISSUE TITLE
Can't run wiLink after succesful build.

### ISSUE THREAD

**Issue by gakwaya** [jlaine/wilink#4]
Hello,

 I am trying to build wiLink ,I have followed the instructions on your README file and it built succesfully on my Ubuntu Debian machine.When I try to execute the generated binary I get the following ouput saying module "wiLink" is not installed.Is there any other step required to get this running?I am building on a 64bit system if this is relevant.

root@murugo:/home/gakwaya/wilink/wilink/build/src/app# ./wiLink 
Window loading https://download.wifirst.net/public/wiLink/2.4.2/qml/boot.qml
https://download.wifirst.net/public/wiLink/2.4.2/qml/boot.qml:21:1: module "wiLink" is not installed 
Window loading qrc:/qml/boot.qml
qrc:/qml/boot.qml:21:1: module "wiLink" is not installed 

Thank you for your time.

**Comment by jlaine** [comment]
This is because you did not install the package, so the executable cannot find the plugin (wiLink.so).

The easiest is to generate a Debian package using "dpkg-buildpackage" and installing the resulting .deb

**Comment by gakwaya** [comment]
Thanks ,I installed the rulting .deb as you said and I am seeing a wiLink icon in my search bar.But when I click on it nothing happens.Is there any other step involved in getting wiLink to run succesfully?

![screenshot from 2015-09-01 19 48 19](https://cloud.githubusercontent.com/assets/3991041/9603303/6ddf45d0-50e2-11e5-8f63-8f5f79344721.png)

Thank you for your time.
