### ISSUE TITLE
Build fails with ‘class QXmppIceConnection’ has no member named ‘gatheringState’

### ISSUE THREAD

**Issue by Spike29** [jlaine/wilink#7]
When trying to build wiLink 2.4.906 on Linux with all dependencies installed and the following commands:
- mkdir build && cd build
- qmake-qt5 WILINK_SYSTEM_QXMPP=1 ..
- make

the build fails with the following errors (QXMPP 0.9.2 is installed): 

<i>../../../../src/imports/wiLink/phone/sip.cpp: Dans la fonction membre ‘void SipCall::gatheringStateChanged()’:
../../../../src/imports/wiLink/phone/sip.cpp:588:27: erreur: ‘class QXmppIceConnection’ has no member named ‘gatheringState’
         d->iceConnection->gatheringState() == QXmppIceConnection::CompleteGatheringState) {
                           ^
../../../../src/imports/wiLink/phone/sip.cpp:588:47: erreur: ‘CompleteGatheringState’ is not a member of ‘QXmppIceConnection’
         d->iceConnection->gatheringState() == QXmppIceConnection::CompleteGatheringState) {
                                               ^
Makefile:962 : la recette pour la cible « sip.o » a échouée
make[3]: *** [sip.o] Erreur 1
make[3] : on quitte le répertoire « /home/yannick/Téléchargements/wilink-2.4.906/build/src/imports/wiLink »
Makefile:42 : la recette pour la cible « sub-wiLink-make_first » a échouée
make[2]: *** [sub-wiLink-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/yannick/Téléchargements/wilink-2.4.906/build/src/imports »
Makefile:87 : la recette pour la cible « sub-imports-make_first-ordered » a échouée
make[1]: *** [sub-imports-make_first-ordered] Erreur 2
make[1] : on quitte le répertoire « /home/yannick/Téléchargements/wilink-2.4.906/build/src »
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make: *** [sub-src-make_first] Erreur 2</i>

**Comment by jlaine** [comment]
Your system's version of qxmpp is too old. I would recommend you use the bundled one until your distro catches up

**Comment by tuxayo** [comment]
What version is needed? (It can't find in the requirements)

**Comment by jlaine** [comment]
If you *want* to use the system's qxmpp, it will have to be 0.9.3 (not yet released)

**Comment by jlaine** [comment]
For your information QXmpp 0.9.3 has been uploaded to Debian/unstable.

**Comment by Spike29** [comment]
Thanks for releasing QXmpp 0.9.3, wiLink compiles as expected now :)

Both qxmpp 0.9.3 and wiLink 2.4.906 are now available in the Archlinux User Repository.

**Comment by tuxayo** [comment]
Hourray for you two !
